### ISSUE TITLE
Better error message when a program type is missing

### ISSUE THREAD

**Issue by sim51** [jacomyal/sigma.js#1300]
When a program is missing, Sigma rises errors like that :

```
this.nodePrograms[data.type] is undefined
```

```
sigma.js:622 Uncaught TypeError: Cannot read properties of undefined (reading 'process')
    at Sigma.process (sigma.js:622:1)
    at Sigma._refresh (sigma.js:698:1)
    at sigma.js:720:1
 ```

I'm sure we can do better, and it will help a lot the community.

Step to reproduce  : 

- on a node, add a property `type` with the value `abc` for example 
- try to visualize the graph

codesandbox: https://codesandbox.io/s/priceless-dream-isljdv?file=/src/index.ts:538-544

**Comment by sim51** [comment]
Closing, same as #1248 and has been already fixed but not released
