### ISSUE TITLE
Error after success install

### ISSUE THREAD

**Issue by swinghu** [jacomyal/sigma.js#724]
npm install runs success, However run npm start, occurs below:

```
Starting up http-server, serving ./
Available on:
  http:192.168.10.170:8000
  http:127.0.0.1:8000
Hit CTRL-C to stop the server
[Thu, 10 Mar 2016 03:53:37 GMT] "GET /" "Mozilla/5.0 (Windows NT 6.1; WOW64) App
leWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
_http_outgoing.js:351
      throw new TypeError('The header content contains invalid characters');
      ^

TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
    at ResponseStream.(anonymous function) [as setHeader] (D:\DevSpace\sigma.js\
node_modules\http-server\node_modules\union\lib\response-stream.js:88:34)
    at D:\DevSpace\sigma.js\node_modules\http-server\node_modules\ecstatic\lib\e
cstatic\showdir.js:43:13
    at FSReqWrap.oncomplete (fs.js:82:15)

```

**Comment by Yomguithereal** [comment]
Hello @swinghu. This is quite weird and seems to relate to the `http-server` dependency. Unfortunately I am unable to reproduce this bug on my end. Can you give me your node & npm version please.

On a related notice, the `npm start` command only serves the repo folder on the 8000 port, so if you need to bypass this bug, just serve it differently using python SimpleHTTPServer or even apache.

**Comment by lj8385174** [comment]
Hey, I think it is a common error on non-English windows system. I have googled, there are several same errors happens in this situation, like  [TypeError: The header content contains invalid characters](https://github.com/npm/npm/issues/11515#)  and  [Karma middleware causing bug for non-english windows environment (The header content contains invalid characters)](https://github.com/karma-runner/karma/issues/1994)

**Comment by lj8385174** [comment]
I find a solution in 'https://github.com/indexzero/http-server/issues/244'

**Comment by Yomguithereal** [comment]
Should we update the dependency to fix this then?
