### ISSUE TITLE
"this undefined" error when using npm link and webpack

### ISSUE THREAD

**Issue by olingerc** [jacomyal/sigma.js#809]
Since 1.2.0 I read that webpack and require statements should work nicely. I use webpack with babel. I tried
```npm install sigma```
and
```import sigma from 'sigma';```
and it works.

Since I would like to start hacking on sigma itself I thought I could use npm link. so I did:
```git clone https://github.com/jacomyal/sigma.js.git``` outside of my project dir and changed into the sigma directory, then:
```npm install && npm run build```
```sudo npm link # i'm on ubuntu```
then back into my project folder I uninstall the sigma module from npm and do:
```npm link sigma```
when starting my webpack build I now get this error:
```
ERROR in ../sigma.js/build/sigma.require.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/christophe/workspace/velona/sigma.js/build"
    at /home/christophe/workspace/velona/velona/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/christophe/workspace/velona/velona/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/christophe/workspace/velona/velona/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/christophe/workspace/velona/velona/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/christophe/workspace/velona/velona/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/christophe/workspace/velona/velona/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/christophe/workspace/velona/velona/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/christophe/workspace/velona/velona/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/christophe/workspace/velona/velona/node_modules/babel-loader/lib/index.js:41:20)
 @ ./src/public/app/genseqhub/genseqhub.component.js 24:13-29
```

I change back into the sigma folder and do
```npm install babel-preset-es2015```
now the webpack build step works
my chrome console shows:
```Cannot read property 'sigma' of undefined```
the responsible part in sigma.core.js is:
```
  /**
   * EXPORT:
   * *******
   */
  if (typeof this.sigma !== 'undefined')
    throw 'An object called sigma is already in the global scope.';

  this.sigma = sigma;

}).call(this);
```

Would anybody have a solution for this? How come the same code works in the npm version but not the linked version?

**Comment by Yomguithereal** [comment]
This is strange indeed and seems to be a babel bug rather than a sigma one since sigma does not use babel whatsoever.
